
openapi: "3.0.0" 
info: 
    title: "Calendar API"
    description: In order to test the protected routes you can use the follow token `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThiZWQ3N2YzNDBmNzNiMjU0MjI5NDIiLCJpYXQiOjE2MzY1NjM1NTZ9.dHL7eH685RmXaGz0t939mZUPInfq0cteySN-_7rBvLM`
    version: "1.0.0"
    description: "A Calendar API to register Appointments"  
servers: 
    - url: http://127.0.0.1:5005/api/
schemes: [http, https]

paths:
    /appointments/:
        get:
            summary: Returns all appointments
            tags: [Appointments]
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/Appointment'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 618586db57866c6ED7590457
                                hour: 17:00
                                day: 20
                                month: April
                                year: 2024
                                isAccepted: null
                                __v: 0
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
        post:
            summary: Posts an appointment
            description: Creates a new appointment
            tags: [Appointments]
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - in: body
              name: appointment
              required: true
              schema:
                $ref: '#/components/schemas/Appointment'
            responses:
                201:
                    description: Created
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/Appointment'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 6189856e19e4a56e42a32330
                                hour: 15:00
                                day: 19
                                month: January
                                year: 2021
                                isAccepted: null
                                __v: 0
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             type: object
                             properties:
                                    error:
                                        type: string
                            example:
                                Year: Year is required
                                Error: Year must be equal or higher then 2021
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error

    /appointments/{id}:
        get:
            summary: Returns an appointment by ID
            description: returns an appointment by ID
            parameters:
            - name: id
              in: path
              description: ID of the Appointment
              required: true

            tags: [Appointments]
            application/json:
                schemas:
                    $ref: '#components/schemas/Appointment'
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/Appointment'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 6189856e19e4a56e42a32330
                                hour: 15:00
                                day: 19
                                month: January
                                year: 2021
                                isAccepted: null
                                __v: 0
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                errors:
                                    year: year is required
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
        put:
            summary: Edits an appointment by ID
            description: edits an appointment by ID
            tags: [Appointments]
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - name: id
              in: path
              description: ID of the Appointment
              required: true
            - in: body
              name: appointment
              required: true
              schema:
                $ref: '#/components/schemas/Appointment'
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/Appointment'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 6189856e19e4a56e42a32330
                                hour: 15:00
                                day: 19
                                month: January
                                year: 2021
                                isAccepted: null
                                __v: 0
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
        delete:
            summary: Deletes an appointment by ID
            description: deletes an appointment by ID
            parameters:
            - name: id
              in: path
              description: ID of the Appointment
              required: true

            tags: [Appointments]
            application/json:
                schemas:
                    $ref: '#components/schemas/Appointment'
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/Appointment'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 6189856e19e4a56e42a32330
                                hour: 15:00
                                day: 19
                                month: January
                                year: 2021
                                isAccepted: null
                                __v: 0
                404:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                errors:
                                    year: year is required
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
    /user/all:
        get:
            summary: Returns all Users
            tags: [Users]
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/User'
                            example:
                                user_data:
                                    agent_id: 7
                                _id: 61893d229df8d50dbd50faaa
                                username: admin
                                email: email
                                password: $2a$10$CjPnCG2lh/EBKAIa0k6DYuSYhixK5Amf7TsdTjjQfG7PutYDAKErG
                                __v: 0
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
    /user/{id}:
        get:
            summary: Gets a user by his id
            description: Gets a user by his id
            tags: [Users]
            security:
                - bearerAuth: []
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - name: id
              in: path
              description: ID of the Agent
              required: true
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/User'
                            example:
                                _id: 61893d229df8d50dbd50faaa
                                username: admin
                                email: email
                                password: $2a$10$CjPnCG2lh/EBKAIa0k6DYuSYhixK5Amf7TsdTjjQfG7PutYDAKErG
                                __v: 0
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             type: object
                             properties:
                                    error:
                                        type: string
                            example:
                                Year: Invalid User ID
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
        put:
            summary: Edits an user by ID
            description: edits an user by ID
            tags: [Users]
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - name: id
              in: path
              description: ID of the User
              required: true
            - in: body
              name: user
              required: true
              schema:
                $ref: '#/components/schemas/User'
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/User'
                            example:
                                _id: 618bed77f340f73b25422942
                                username: Api Test User
                                email: test@api.com
                                password: $2a$10$N48xoyVhZEwe2tNN/mO/HOOBYvm39zXCdvuecp8lj0JxIo0WN6nn.
                                __v: 0
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                errors: email is required
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                404:
                    description: Not Found
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                error: user not found
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error
        delete:
            summary: Deletes an user by ID
            description: deletes an user by ID
            parameters:
            - name: id
              in: path
              description: ID of the user
              required: true
            tags: [Users]
            application/json:
                schemas:
                    $ref: '#components/schemas/User'
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Sucess: User testuser with ID 618bd9fdfd9de4ab30db63b6 deleted from Database
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Unauthorized, access token is missing or invalid
                404:
                    description: Not Found
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                error: user not found
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error

    /user/register:
        post:
            summary: Creates a new User
            description: Creates a new user
            tags: [Users]
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - name: user
              in: body
              required: true
              schema:
                $ref: '#/components/schemas/User'
            responses:
                201:
                    description: Created
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/User'
                            example:
                                _id: 618bed77f340f73b25422942
                                username: Api Test User
                                email: test@api.com
                                password: $2a$10$N48xoyVhZEwe2tNN/mO/HOOBYvm39zXCdvuecp8lj0JxIo0WN6nn.
                                __v: 0
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Errors:
                                    email: email is required
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error

    /user/login:
        post:
            summary: User Login
            description: allows the user to login, in order to get a valid token for the protected routes
            tags: [Users]
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
            - in: body
              name: user
              required: true
              schema:
                type: object
                properties:
                    email:
                        type: string
                    password:
                        type: string
                example:
                    email: test@api.com
                    password: 324872332
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/User'
                            example:
                                userId: 618bed77f340f73b25422942
                                Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThiZWQ3N2YzNDBmNzNiMjU0MjI5NDIiLCJpYXQiOjE2MzY1NjM1NTZ9.dHL7eH685RmXaGz0t939mZUPInfq0cteySN-_7rBvLM
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Errors:
                                    email: email or password is wrong
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schemas:
                             $ref: '#components/schemas/error'
                            example:
                                Error: Internal server error

# components 
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: http
    schemas:
        Appointment:
            type: object
            properties:
                user_data:
                    type: object
                    properties:
                        agent_id:
                            type: number
                hour:
                    type: string
                day:
                    type: number
                month:
                    type: string
                year:
                    type: number
            examples:
                user_data:
                    agent_id: 7
                _id: 618586db57866c6ED7590457
                hour: 17:00
                day: 20
                month: April
                year: 2024
                isAccepted: null
                __v: 0
        User:
            type: object
            properties:
                username:
                    type: string
                email:
                    type: string
                password:
                    type: string
        error:
            type: object
            properties:
                error:
                    type: string

